POST http://localhost:4700/projects
Content-Type: application/json

{
    "note_title":"Recite Quran",
    "note_content":"I will recite quran for eight hours tommmorrow"
}


### GET ONE Note
GET http://localhost:4700/projects/


###GET ALL NOTES
GET http://localhost:4700/projects


###UPDATE a NOTE
PUT http://localhost:4700/projects/5c67e259-e4ba-44ec-9e18-c81807557793
Content-Type: application/json

{
    "note_title":"Study ",
    "note_content":"i am studying this concepts"
}


###DELETE A NOTE
DELETE http://localhost:4700/projects/f40c5e1a-5439-4b68-8ec1-97e16446eed9


###Register User
POST http://localhost:4700/user
Content-Type: application/json

{
    "username":"AbdulRaheem M",
    "email":"davidmunyiri2019@gmail.com",
    "password":"12345678"
}


###Login User
POST http://localhost:4700/user/login
Content-Type: application/json

{
    "username":"David Munyiri",
    "password":"1234567890"
}